functionsDirectory = "/Users/thomasmadden/dev/tommys-thoughts/server"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/thomasmadden/dev/tommys-thoughts/build"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "/Users/thomasmadden/dev/tommys-thoughts/server"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]